// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/takumin/go-netbox/models"
)

// DcimConnectedDeviceListReader is a Reader for the DcimConnectedDeviceList structure.
type DcimConnectedDeviceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimConnectedDeviceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimConnectedDeviceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimConnectedDeviceListOK creates a DcimConnectedDeviceListOK with default headers values
func NewDcimConnectedDeviceListOK() *DcimConnectedDeviceListOK {
	return &DcimConnectedDeviceListOK{}
}

/*DcimConnectedDeviceListOK handles this case with default header values.

DcimConnectedDeviceListOK dcim connected device list o k
*/
type DcimConnectedDeviceListOK struct {
	Payload *models.Device
}

func (o *DcimConnectedDeviceListOK) Error() string {
	return fmt.Sprintf("[GET /dcim/connected-device/][%d] dcimConnectedDeviceListOK  %+v", 200, o.Payload)
}

func (o *DcimConnectedDeviceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Device)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
