// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/takumin/go-netbox/models"
)

// DcimPowerFeedsCreateReader is a Reader for the DcimPowerFeedsCreate structure.
type DcimPowerFeedsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPowerFeedsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewDcimPowerFeedsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimPowerFeedsCreateCreated creates a DcimPowerFeedsCreateCreated with default headers values
func NewDcimPowerFeedsCreateCreated() *DcimPowerFeedsCreateCreated {
	return &DcimPowerFeedsCreateCreated{}
}

/*DcimPowerFeedsCreateCreated handles this case with default header values.

DcimPowerFeedsCreateCreated dcim power feeds create created
*/
type DcimPowerFeedsCreateCreated struct {
	Payload *models.PowerFeed
}

func (o *DcimPowerFeedsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /dcim/power-feeds/][%d] dcimPowerFeedsCreateCreated  %+v", 201, o.Payload)
}

func (o *DcimPowerFeedsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PowerFeed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
