// Code generated by go-swagger; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasCustomFieldChoicesListReader is a Reader for the ExtrasCustomFieldChoicesList structure.
type ExtrasCustomFieldChoicesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomFieldChoicesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasCustomFieldChoicesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasCustomFieldChoicesListOK creates a ExtrasCustomFieldChoicesListOK with default headers values
func NewExtrasCustomFieldChoicesListOK() *ExtrasCustomFieldChoicesListOK {
	return &ExtrasCustomFieldChoicesListOK{}
}

/*ExtrasCustomFieldChoicesListOK handles this case with default header values.

ExtrasCustomFieldChoicesListOK extras custom field choices list o k
*/
type ExtrasCustomFieldChoicesListOK struct {
}

func (o *ExtrasCustomFieldChoicesListOK) Error() string {
	return fmt.Sprintf("[GET /extras/_custom_field_choices/][%d] extrasCustomFieldChoicesListOK ", 200)
}

func (o *ExtrasCustomFieldChoicesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
