// Code generated by go-swagger; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasReportsListReader is a Reader for the ExtrasReportsList structure.
type ExtrasReportsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasReportsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasReportsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasReportsListOK creates a ExtrasReportsListOK with default headers values
func NewExtrasReportsListOK() *ExtrasReportsListOK {
	return &ExtrasReportsListOK{}
}

/*ExtrasReportsListOK handles this case with default header values.

ExtrasReportsListOK extras reports list o k
*/
type ExtrasReportsListOK struct {
}

func (o *ExtrasReportsListOK) Error() string {
	return fmt.Sprintf("[GET /extras/reports/][%d] extrasReportsListOK ", 200)
}

func (o *ExtrasReportsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
