// Code generated by go-swagger; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasCustomFieldChoicesReadReader is a Reader for the ExtrasCustomFieldChoicesRead structure.
type ExtrasCustomFieldChoicesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomFieldChoicesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasCustomFieldChoicesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasCustomFieldChoicesReadOK creates a ExtrasCustomFieldChoicesReadOK with default headers values
func NewExtrasCustomFieldChoicesReadOK() *ExtrasCustomFieldChoicesReadOK {
	return &ExtrasCustomFieldChoicesReadOK{}
}

/*ExtrasCustomFieldChoicesReadOK handles this case with default header values.

ExtrasCustomFieldChoicesReadOK extras custom field choices read o k
*/
type ExtrasCustomFieldChoicesReadOK struct {
}

func (o *ExtrasCustomFieldChoicesReadOK) Error() string {
	return fmt.Sprintf("[GET /extras/_custom_field_choices/{id}/][%d] extrasCustomFieldChoicesReadOK ", 200)
}

func (o *ExtrasCustomFieldChoicesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
